title: Ali Saqallah
logo: /assets/img/headshot.png
description: Data analyst with a master
and visualization. Proficient in Python and statistical methods, experienced in extracting actionable insights from complex datasets.
show_downloads: false
theme: jekyll-theme-minimal
